### ISSUE TITLE
Confirmed transaction not showing up in sender's transaction history

### ISSUE THREAD

**Issue by yknl** [hirosystems/stacks-blockchain-api#1058]
The transaction below does not show up in the transactions endpoint for the sender address:

Transaction:
https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/0xcab4e56dc1210de5ba5b3dabcc104f1a44079fb6ea9a212da13801815a001c6a

Sender:
https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SPAV5PXNEZ44AH4RDP7JX7WEG9Y8N0BFY411VT51/transactions

**Comment by rafaelcr** [comment]
I found the problem here.

The transaction in question was originally confirmed in a canonical microblock off a non-canonical block, causing it not to be included in the `principal_stx_txs` table. However, that non-canonical block was later moved to the canonical chain via a re-org, causing the transaction to become canonical but still missing from the `principal_stx_txs` table which feeds the `/transactions` endpoint. That's why you don't see it.

I'm working on a PR to handle this edge case. cc @zone117x
