### ISSUE TITLE
prune mempool transactions if older than 256 blocks from chain tip

### ISSUE THREAD

**Issue by Hero-Gamer** [hirosystems/stacks-blockchain-api#1059]
**Describe the bug**
(Sleepi asked me to file this issue...)
I will cause they are still in there. 🙏 
https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool?offset=400
Most of them are receipt on 04Feb
"receipt_time_iso": "2022-02-04T09:57:40.000Z"

**Comment by rafaelcr** [comment]
@CharlieC3 could this possibly be related to the event replay issue we were discussing yesterday? (TSV showing weirdness around 4-Feb)

**Comment by wileyj** [comment]
@sleepiJoe

**Comment by sleepiJoe** [comment]
The txs are still not pruned from the mempool leading to unrepresentative values in different statistics:
![image](https://user-images.githubusercontent.com/94863769/154861270-51d1d141-c95e-4ae1-b038-a66b66ad776c.png)
(Source: [https://stacksdata.info/#mempool](https://stacksdata.info/#mempool))
[https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool?offset=700](https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool?offset=700)

What is happening here? 
I fist thought this event would vanish very quickly, now I only see it stuck in place.

@rafaelcr Can you go into detail about what you are referring to?

**Comment by zone117x** [comment]
A couple notes about mempool txs in the API:
* The `/new_mempool_tx` event from the stacks-node is sent without any reference to time or block height. When the API receives the event, it creates a timestamp with the current time e.g. `Date.now()` and stores it in the db. This works okay while the API is running and fully synced. However, during event-reply, all mempool txs replayed will have a timestamp of when the event-replay happened. Likely explains the entries mentioned above that show `"receipt_time_iso": "2022-02-04...`.

* Mempool txs do not get pruned from the API database unless the txid is included in a canonical block/microblock, _or_ unless a `/drop_mempool_tx` event is received for the tx. This means there are likely two ways in which a mempool tx can appear "unpruned" in the API database indefinitely:
  1. The `/new_mempool_tx` and `/drop_mempool_tx` events are both generally unreliable in that they are emitted in a non-deterministic cadence, there isn't always a perfect 1-to-1 between them, they can be out of order, they are easily dropped during stacks-node restarts, etc. So there can easily be situations in which something like a barrage of mempool tx events are received in unexpected ways, like a `/drop_mempool_tx` event being received for an RBF'd tx before the original tx is received from a `/new_mempool_tx` event.
  2. Secondly, when blocks/microblocks are orphaned, the API needs to "un-prune" mempool transactions as part of it's re-org handling. As in, if a mempool tx `Y` is included in microblock `A`, then tx `Y` will be pruned, if microblock `A` is orphaned then tx `Y` will be "restored" in the mempool until/unless it is included in a micro/block again. The stacks-node does similar operations to the mempool doing re-orgs, but likely not identical, and there is certainly opportunity for discrepancies. Either due to mempool "restoration" being too aggressive or bugged, or simply the follow-up `/drop_mempool_tx` or `/new_mempool_tx` events aren't received in an expected way after these types of situations.


IMO there's two approaches to addressing these issues:
1. Implement mempool prune functionality within the API that operates as a catch-all for any mempool txs that slip through the cracks mentioned above. It can be ran when a new block is processed, and simply prune all txs from the mempool older than X hours.
2. Start a long game of whack-a-mole in trying to add additional complexity to the API event ingestion to try to handle all the various edge-cases. I'm skeptical of this approach ever working out, because it seems like there will always be yet another unexpected cadence of events resulting in "indefinite" mempool txs, _or_ the changes will be too aggressive in pruning and result in even worse bugs for users where their mempool tx "disappears" because it's too eagerly pruned.

I think we should go ahead with the first approach of self-pruning old mempool txs. 

Additionally, we should open a feature request to the stacks-node to include either a timestamp or block height in the `/new_mempool_tx` event payload, so the event-stream can act as the source of truth, rather than the API having to infer the time, which causes issues during event-replay.

**Comment by zone117x** [comment]
As an aside note, I recommend dashboards like https://stacksdata.info/#mempool to be built in a way where they represent the mempool source-of-truth as accurately as possible. Which in this case, would generally mean something like query the stacks-node directly (assuming an RPC or p2p method is possible), or reading from the stacks-node own sqlite db. 

Likewise, I do _not_ recommend the mempool API endpoints or postgres db to be used when creating historical mempool visualizations / dashboards.

The mempool events, and by extension the API mempool endpoints like `https://stacks-node-api.mainnet.stacks.co/extended/v1/tx/mempool`, are likely never going to be a perfect historical representation of the mempool. The mempool events and the mempool API endpoints are both designed for getting mempool txs displayed to clients as quickly as possible. This is their primary use-case. Historical mempool visualizations don't need to worry about recency requirements like this, and can focus on gathering an accurate snapshot of the mempool on an interval.

**Comment by rafaelcr** [comment]
@zone117x 

> I think we should go ahead with the first approach of self-pruning old mempool txs.

I agree with this completely. I also think there's a lot of room for improvement in the way we currently do event replay, because we're still processing mempool events that are way too old to be relevant to the actual state of the mempool at chain tip i.e. we could set a threshold at which to drop old mempool txs in a running API and use that same threshold to ignore all older mempool events during replay.

**Comment by saralab** [comment]
Break this into : 
- Optimsing event replay 
- Self prune mempool tx- [this issue]

**Comment by rafaelcr** [comment]
@zone117x when we do mempool pruning > 256 blocks, could we `DELETE` those rows from the `mempool_txs` table instead of just marking them as `pruned = true`? This could save us a huge amount of space from this table and make its queries much faster.
