### ISSUE TITLE
inconsistent tx data across public API instances

### ISSUE THREAD

**Issue by pseudozach** [hirosystems/stacks-blockchain-api#1119]
Running `/extended/v1/address/SP2507VNQZC9VBXM7X7KB4SF4QJDJRSWHG4V39WPY.stxswap_v8/transactions` endpoint gives different values
- https://stacks-node-api.stacks.co/extended/v1/address/SP2507VNQZC9VBXM7X7KB4SF4QJDJRSWHG4V39WPY.stxswap_v8/transactions: "total": 642
- [my node](http://api.lnswap.org:3999/extended/v1/address/SP2507VNQZC9VBXM7X7KB4SF4QJDJRSWHG4V39WPY.stxswap_v8/transactions): "total": 656 
- https://mainnet.syvita.org/extended/v1/address/SP2507VNQZC9VBXM7X7KB4SF4QJDJRSWHG4V39WPY.stxswap_v8/transactions: "total": 686 -> seems to be the most realistic
- https://stacks-node-api.alexlab.co/extended/v1/address/SP2507VNQZC9VBXM7X7KB4SF4QJDJRSWHG4V39WPY.stxswap_v8/transactions: "total": 686,

- I'm guessing similar inconsistent results will happen for other data as well which could be a problem as user facing apps depend on this data.
- Note that in my case I've indeed done `event replay` to upgrade from 2.05 to 2.05.1 for the lnswap node so it could be related.
- Another (possibly related) issue is that I've seen same txid twice in the stacks.co instance:
Loop through and save all transactions for the above endpoint into a json file
You can see this txid: `0x04bcbe61f525f795ca736e7ca44213081763f907f39be378d22e0db263deb995` twice on 2 blockheights `"block_height": 45852,` and `"block_height": 45853,` and same nonce `245`

cc @rafaelcr

**Comment by caoer** [comment]
@rafaelcr 
I think it might not be caused from stacks-node or reply. I did see the error logs while replay the events regarding sending duplicated events and inserting the same tx_id into the mempool. 

however, with [a simple script](https://gist.github.com/caoer/7e35e137d2de1efaedd318233bb4d245) to check for the missing txs between 1.0.x and 3.0.x. we can find out what is missing in the newer API: 

it looks like that the tx is only missing from `/extended/v1/address/{principal}/transactions` endpoint, however, we can still get the tx directly by calling `extended/v1/tx/{tx_id}`, the transactions is not missing in the db, but we just can not get it from transactions list API endpoint.

**Comment by caoer** [comment]
I uploaded the missing txs in https://github.com/hirosystems/stacks-blockchain-api/issues/1098 and review all of them, seems like they should be able to be included.

**Comment by caoer** [comment]
One side note while reading the source code, I recommend you guys to check out [getdbt](https://www.getdbt.com/), which is an awesome tool to build and test complex data views.  It is not a trivial task to integrate but definitely worth to explore the option.

**Comment by CharlieC3** [comment]
Interesting, thanks for the insight @caoer. It looks like the Syvita and Alex APIs are running an older version, 1.0.7 and 1.0.6 respectively.
So you're suggesting either a data view in the DB has changed between version 1.0.7 to Hiro's deployed version 3.0.2, or the query itself has changed in such a way that it no longer returns the complete data set?

Is it possible that the old versions are the ones that are incorrect? There's been plenty of bug fixes since their deployed versions, it possible the old data views were incorrect and the most recent version hosted by Hiro is more accurate.

@rafaelcr Do you have an easy way to compare these differences and confirm whether Hiro's data view (3.0.2) is correct or incorrect for these endpoints? I'm not sure how difficult it is to get `getdbt` integrated to our CI process, but until then I'm happy to help with the investigation.

**Comment by rafaelcr** [comment]
Thanks for the data @caoer , it will be very valuable for the tests I'll be making.
Answering a few key points:

> I did see the error logs while replay the events regarding sending duplicated events and inserting the same tx_id into the mempool.

That is not unexpected. Sometimes the stacks node will send duplicate events for a series of reasons, and those logs are normal when we drop a repeated event, etc.

> it looks like that the tx is only missing from /extended/v1/address/{principal}/transactions endpoint, however, we can still get the tx directly by calling extended/v1/tx/{tx_id} on both versions of API, the transactions is not missing in the db, but we just can not get it from transactions list API endpoint

This is great, thank you. I checked the zip file you added and I'm testing some of those txs. @CharlieC3 is right by saying that generally a higher API version means bugs were fixed thus leading to better results. Nevertheless, from 1.x to 3.x there have been several changes in how we do queries by the use of caching tables (for performance reasons), and those changes can most definitely have obscure edge cases that we haven't yet considered. Going back to the old queries from 1.x is unfeasible because they are just too expensive and impossible to scale with Hiro's current API traffic loads.

I suspect there is still one chain re-org case that is not being correctly reflected in the `/transactions` endpoint, but I'm still investigating to confirm.

> however, with [a simple script](https://gist.github.com/caoer/7e35e137d2de1efaedd318233bb4d245) to check for the missing txs between 1.0.x and 3.0.x. we can find out what is missing in the newer API:

This is great, thank you. We could use something like this to quickly test against old API versions in the future.
