### ISSUE TITLE
Render new TSV based on already re-orged events and use that to replay

### ISSUE THREAD

**Issue by rafaelcr** [hirosystems/stacks-blockchain-api#1160]

**Comment by smcclellan** [comment]
@zone117x What's blocking this one?

**Comment by zone117x** [comment]
Nothing is blocking this. The WIP PR https://github.com/hirosystems/stacks-blockchain-api/pull/1166 was pretty close at the time, but the codebase and schema has changed quite a bit since that PR. Merging in latest and bringing it to the finish line is still probably a medium-large sized effort that we'd need to prioritize.

**Comment by CharlieC3** [comment]
@smcclellan Should this be closed?

**Comment by csgui** [comment]
@sabbyanandan The new event-replay implementation still relay on the TSV parsing to Parquet. An improvement yet to be discussed is the direct generation and archival of parquet files (instead of TSVs).

#1166 is deprecated. The new PR for the event-replay stuff is #1694.
