### ISSUE TITLE
BNS name renewal ->new expired_block value

### ISSUE THREAD

**Issue by sleepiJoe** [hirosystems/stacks-blockchain-api#1176]
**Describe the bug**
Wrong data for `expire_block` of [this endpoint](https://docs.hiro.so/api#operation/get_name_info).

**To Reproduce**
1. Go to ['the endpoint'](https://stacks-node-api.mainnet.stacks.co/v1/names/friedger.id)
2. Review line `"expire_block": 52595,`
3. See error

**Expected behavior**
BNS name renewal/new expired_block value should be visible at this endpoint.

**Comment by friedger** [comment]
The name was renewed at block 51951
https://explorer.stacks.co/txid/0xf037c8da8210e2a348bbecd3bc44901de875d3774c5fce49cb75d95f2dc2ca4d?chain=mainnet

**Comment by rafaelcr** [comment]
looping in @lgalabru who might have some more context here...

Ludo, do you know if we get an event when a name renewal happens? Either an event emitted by the BNS contract or a new attachment from the Stacks node event emitter?

I looked directly at our postgres database to see which events we currently have in the `names` table for `friedger.id` and we only have the name registration, not the renewal. That's why it's returning stale data. Maybe the API is not listening for renewals correctly.

**Comment by friedger** [comment]
For name-update txs at least the attachments are treated.

**Comment by asimm241** [comment]
I have debugged the issue and here are my findings:

1) We haven't received the event for this particular name for 'name-renewal'. even though we should receive 'name-renewal' events. We have a test case for this.  The evidence for that is `last_txid` is not updated and `expire_block` is the same as It was in v1-import data. 

2) We don't recieve `expire_block` value from the node. We have to calculate it. It should calculated as following
`expire_block` = (block at which name `import`/`registered`/`renewed`) + `lifetime` 
`lifetime` is the property of corresponding namespace, in this case it's `id`.  So, we have to calculated after we recieve the event.

3) We don't have mechanism for calculating expire_block. We should make a decision if we shold  **store expire_block** in names table or **calculate expire_block runtime** when is queried for the name by joining with namespace table. 
1st option is easy to implment
2nd Is a little tricky because we don't recieve namespace infromation for name-import so probably have to make contract call to fetch namespace lifetime but not sure.

**Comment by asimm241** [comment]
I could not find the `name-renewal` event in the TSV file which includes the above [transaction](https://explorer.stacks.co/txid/0xf037c8da8210e2a348bbecd3bc44901de875d3774c5fce49cb75d95f2dc2ca4d?chain=mainnet)
In fact, this transaction also does not contain any event for `name-renewal`. 
Although, the BNS contract does emit a name-renewal event https://github.com/stacks-network/stacks-blockchain/blob/db3c7a233e8d7c492ba24c7143b5ac065f58ea9b/src/chainstate/stacks/boot/bns.clar#L268
Moreover, I do receive a name-renewal event when I test it locally. Is this possible that we have received the event but it's not logged?

**Comment by asimm241** [comment]
@rafaelcr The problem is that the event is not received because the zone-file-hash is empty
and bnc contract only sends event if zone file hash is present

```
(if (is-none zonefile-hash)
      (map-set name-properties
        { name: name, namespace: namespace }
        { registered-at: (some block-height),
          imported-at: none,
          revoked-at: none,
          zonefile-hash: (get zonefile-hash name-props) })
      (update-zonefile-and-props
              namespace 
              name
              (some block-height)
              none
              none
              (unwrap-panic zonefile-hash)
              "name-renewal"))  
    (ok true)))
```
Thus the issue is not on the API side. 

Although we still should address the 3rd point from here https://github.com/hirosystems/stacks-blockchain-api/issues/1176#issuecomment-1160383290 for that we should open another issue.

**Comment by saralab** [comment]
- Bug in emitting events, blocked until Blockchain issues are resolved.

**Comment by rafaelcr** [comment]
After talking with @lgalabru, I learned the BNS contract does emit this information [inside a `print` message](https://github.com/stacks-network/stacks-blockchain/blob/08c163bab484954b3934515ee7bf60848f52ed4a/src/chainstate/stacks/boot/bns.clar#L499). From the API, we could read those events and obtain the namespace `lifetime` from the associated properties.

Another option would be to perform a read-only contract call to the BNS contract to [query for this info](https://github.com/stacks-network/stacks-blockchain/blob/08c163bab484954b3934515ee7bf60848f52ed4a/src/chainstate/stacks/boot/bns.clar#L499) later on.
