### ISSUE TITLE
Fetching contract events doesn't include `total`

### ISSUE THREAD

**Issue by hstove** [hirosystems/stacks-blockchain-api#1250]
The [API for fetching contract events](https://hirosystems.github.io/stacks-blockchain-api/#tag/Smart-Contracts/operation/get_contract_events_by_id) doesn't include a `total` property in the JSON response.

I'm building something that requires syncing with a contract's `print` events, and its very important that no events are "skipped". When this app re-syncs with the Stacks API, it looks for "contract events since txid X". It does this by simply paging through the contract events API until it sees its "last synced" transaction. With this mechanism, it's possible that, while paging, the network has a new block mined. This would "corrupt" the pager's "offset" parameter.

My thought was to utilize the `total` property, and to re-sync from the top if the `total` property changed between events, but then I saw that this isn't available on this particular API call.

Is there a better way to ensure that I'm syncing every single event? This use-case doesn't need to be fast - it runs this on a cron-type schedule. It's just more important that it doesn't miss anything.

It would be great for the API to support query params like `since=txid`, which would make this more simple to handle, but I'm sure that would be a much bigger feature.

Thanks!

**Comment by zone117x** [comment]
> It would be great for the API to support query params like `since=txid`, which would make this more simple to handle, but I'm sure that would be a much bigger feature.


A pagination feature like `since=txid` seems reasonable, I need to look into the sql to make sure we can do it fast enough. It seems like `since=block(height/hash)` would be easier to implement with the current schema. Would that work?

> Is there a better way to ensure that I'm syncing every single event?

Seems reasonable -- by "re-sync from the top" do you mean like get latest events until you find one you already have, or a full re-sync?

The one thing I'd recommend, if you don't need to your data to be immediately up to date, is to ignore/skip everything below something like 5 blocks in confirmations. Then you're end wouldn't have to deal with re-orgs.

**Comment by smcclellan** [comment]
Hey @hstove! I'm closing this one due to inactivity. Please reopen if still needed.
