### ISSUE TITLE
Names of new namespaces are not listed on /v1/namespaces/{tld}/names

### ISSUE THREAD

**Issue by friedger** [hirosystems/stacks-blockchain-api#1291]
**Describe the bug**
Calling [the endpoint with crashpunk](https://stacks-node-api.mainnet.stacks.co/v1/namespaces/crashpunk/names) returns an error "No such namespace" even though names exist in that namespace, e.g. friedger.crashpunk: https://stacks-node-api.mainnet.stacks.co/v1/names/friedger.crashpunk

The lookup works as well for a name in the namespace: https://stacks-node-api.mainnet.stacks.co/v1/addresses/stacks/SP82S7H3DPXG6NN2YGW413DSK5Q83BT59E92G1H1

**To Reproduce**
1. Go to https://stacks-node-api.mainnet.stacks.co/v1/namespaces/crashpunk/names

**Expected behavior**
It should list all the registered names

**Additional context**
The name was registered here: https://explorer.stacks.co/txid/0x380ff50ab3f1c5b459bbe934d3f3812a2326e78071e64ecdda3a80f80e638809?chain=mainnet

**Comment by rafaelcr** [comment]
thanks @friedger ... do you have the tx_id of the transaction that registered the namespace?

**Comment by rafaelcr** [comment]
@friedger I think I found an example transaction: https://explorer.stacks.co/txid/0x605aa0554fb5ee7995f9780aa54d63b3d32550b0def95e31bdf3beb0fedefdae?chain=mainnet

The problem here is that the API only recognizes calls made to the BNS contract directly by a TX. In this case, the `SPC0KWNBJ61BDZRPF3W2GHGK3G3GKS8WZ7ND33PS.community-handles-v2` contract is the one calling the BNS contract internally, and in turn it is the one emitting the `print` informing the namespace is ready.

We'll need to make a change on the API to make sure we catch print events that were called by other contracts.
