### ISSUE TITLE
List of addresses "rich list"

### ISSUE THREAD

**Issue by muneeb-ali** [hirosystems/stacks-blockchain-api#131]
I just left this issue on the old explorer:

https://github.com/blockstack/blockstack-explorer/issues/222

Would love to learn about any plans for such a "rich list" for explorer 2.0. There might already be a planned feature for this? If not, we can try to discuss it here. For explorer 1.0, it can be quick and dirty and somewhat manual but for 2.0 this will need to be a feature where addresses update automatically etc.

**Comment by agraebe** [comment]
would this new project resolve the need @muneeb-ali: https://stacksdata.info/ ?

**Comment by sabbyanandan** [comment]
What @agraebe pointed out (though maintained by the community and is very cool, especially the SQL explorer) appears to capture the gist of the original ask indeed. 

@muneeb-ali: would that be sufficient to answer the questions for the community? The desire to have such an endpoint, while doable, may not directly provide incremental value in Explorer right now. Open to hearing other thoughts and ideas where otherwise it could be helpful.

**Comment by diwakergupta** [comment]
@sabbyanandan this is a ~2yr old issue :) Probably fine to just close it out.
