### ISSUE TITLE
Ensure the all-in-one Rosetta docker image is working

### ISSUE THREAD

**Issue by zone117x** [hirosystems/stacks-blockchain-api#1362]
Several lines in https://github.com/hirosystems/stacks-blockchain-api/blob/master/docker/stx-rosetta.Dockerfile appear to be out-of-date. We should test a deployment with this image and make any necessary updates/fixes. 

Additionally, we should look into establishing a testing process so that it doesn't fall behind, especially since major partners in the ecosystem are dependent on this setup.

For example, perhaps Hiro should have a private, low-resource deployment using this image which gets auto-updated on major API version releases.

**Comment by saralab** [comment]
1. Ensure this dockerfile works as is
2. Add automated tests - Long term (not immediate)

**Comment by aravindgee** [comment]
@zone117x @rafaelcr could you review the PR and let me know if it looks good?

**Comment by CharlieC3** [comment]
@zone117x @rafaelcr Bump, any updates on the above?

**Comment by rafaelcr** [comment]
sorry for the delay, will check it out @CharlieC3

**Comment by aravindgee** [comment]
Rebase to master failing, will submit a new PR shortly.

**Comment by aravindgee** [comment]
PR. #1479 is ready - merge pending.

Do we need any other action on this item? (eg. additional testing)

_Additionally, we should look into establishing a testing process so that it doesn't fall behind, especially since major partners in the ecosystem are dependent on this setup._

cc @deantchi @rafaelcr @zone117x
