### ISSUE TITLE
extended/v1/address/{address}/transaction endpoint for specific address on local API takes nearly 60 seconds to respond

### ISSUE THREAD

**Issue by TensionCoding** [hirosystems/stacks-blockchain-api#1535]
**Describe the bug**
I have fully synced STX and BTC nodes and a fully synced STX API on my DigitalOcean server running Debian 10. 
If execute the following request on my server, I get a response in about 2 seconds: `curl -sL 'https://stacks-node-api.mainnet.stacks.co/extended/v1/address/SP1B3VAZJGPBC9CF82TSS4S1WGZXP207JG8MGHQGW/transactions?limit=1&offset=0' | jq`

When I execute the same request to my local API: `curl -sL 'http://localhost:3999/extended/v1/address/SP1B3VAZJGPBC9CF82TSS4S1WGZXP207JG8MGHQGW/transactions?limit=1&offset=0' | jq` the response is closer to 60 seconds.

Here is the API log for the request:
![Screenshot 2023-01-28 at 10 48 19 AM](https://user-images.githubusercontent.com/103322358/215275983-7223ed5a-28ec-4541-aa7f-0dd12066d2e5.png)

As you can see the API is extremely slow in responding to this request.

It is important to note that I am not receiving this type of delay from any other address so far.

**To Reproduce**
1.  `curl -sL 'http://localhost:3999/extended/v1/address/SP1B3VAZJGPBC9CF82TSS4S1WGZXP207JG8MGHQGW/transactions?limit=1&offset=0' | jq`

**Expected behavior**
To receive a response that is as least as performant as the Hiro public API

**Desktop (please complete the following information):**
 - OS: Debian 10
 - Stacks API version 6.2.1 (docker image)
 - Blockchain version 2.05.6.0 (docker image)

**Comment by rafaelcr** [comment]
Hi @TensionCoding , can you share more details about your local postgres setup? e.g. version, if it lives in the same server, etc.

The `/transactions` endpoint is one of the most expensive ones because it needs to JOIN a few tables to get the result. Slowness here is usually because you're either lacking an index (unlikely if you've performed all API migrations normally) or the database is in need of some other maintenance (like a VACUUM or similar to make the hard disk access faster).

A tool you could do to debug is [PgHero](https://github.com/ankane/pghero) , it would give you some diagnostics on your DB instance and may detect some configurations you need to tweak.

**Comment by TensionCoding** [comment]
Hey @rafaelcr, I am running a postgres docker image, version 14-alpine. It is hosted on the same server as the API and blockchain node. The configurations for the postgres DB are the defaults provided by the [Digital Ocean Marketplace](https://marketplace.digitalocean.com/apps/stacks-blockchain).

I will look into PgHero. Thank you.

**Comment by rafaelcr** [comment]
Closing this, feel free to reopen if you have further questions
