### ISSUE TITLE
All TX endpoints show the cache is expired

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#1600]
Etag caching does not seem to be working as expected for TX endpoints.

For example, hitting this endpoint returns the following `cf-cache-status` of EXPIRED:
https://api.hiro.so/extended/v1/tx/0xe4661994dccf80c4268adf6a90931c8897b02176bc255e2e04d587e93f4a7f55
![Screenshot 2023-03-27 at 1 14 49 PM](https://user-images.githubusercontent.com/2747302/228024327-0acf50f6-80b5-4081-9a88-f6ef34820362.png)

Instead, I would expect it to work like the `[status](https://api.hiro.so/extended/v1/status)` endpoint and return REVALIDATED like so:
![Screenshot 2023-03-27 at 1 36 59 PM](https://user-images.githubusercontent.com/2747302/228024398-468b4da9-7d13-47f1-bee6-1b6407bd0c29.png)

I'm not sure if etag caching is broken for other endpoints too, so this should be verified across the board just to be sure.

**Comment by zone117x** [comment]
@CharlieC3 caching on this endpoint appears to be working as expected. If you're using Chrome network activity tab, you'll want to look at the `Status` and `Size` columns in the request table view. When the response it cached, it will show `Status: 304 (Not Modified)` and `Size: <few hundred bytes>` (size should be tiny because the cached response only returns headers and no body).

For example:
<img width="541" alt="image" src="https://user-images.githubusercontent.com/1447546/228293624-f03438ef-e3aa-4df6-a6e3-f5ca0b1e3850.png">

When you click the actual table row entry for the network request, the UI is somewhat unintuitive in that it shows the `Response Headers` and `Preview (body)` for the _previously cached_ response rather than the actual response. 

IIUC the `cf-cache-status: EXPIRED | REVALIDATED` header is related to what happened inside cloudflare's LRU cache system. Cloudflare's internal proxy cache evicts based off recency+size but exact behavior is a black box. In other words, cloudflare can evict cache for a given url despite the etag or other cache headers indicating that the cache is still valid.

**Comment by CharlieC3** [comment]
@zone117x Strange, I'm not seeing what you are. For example, all my responses are `200` regardless of the endpoint, how many times I refresh, browser cache enabled/disabled, or the `cf-cache-status` header reading EXPIRED or REVALIDATED.

https://api.hiro.so/extended/v1/tx/0xe4661994dccf80c4268adf6a90931c8897b02176bc255e2e04d587e93f4a7f55
![Screenshot 2023-04-03 at 10 51 58 AM](https://user-images.githubusercontent.com/2747302/229546691-94ce89cd-80a8-4491-a777-4d8df8f1b2c8.png)

https://api.hiro.so/extended/v1/status
![Screenshot 2023-04-03 at 10 52 17 AM](https://user-images.githubusercontent.com/2747302/229546790-31634851-0f22-4026-93d3-84178e8ad4e7.png)

https://api.hiro.so/v2/info
![Screenshot 2023-04-03 at 10 52 55 AM](https://user-images.githubusercontent.com/2747302/229546964-92b53c5c-ee6a-4ca5-8eb1-b397e2bc1416.png)

What odd though is the `etag` returned between the `extended/v1/tx/0xe4661994dccf80c4268adf6a90931c8897b02176bc255e2e04d587e93f4a7f55` and `extended/v1/status` endpoints is different. The former is a much longer etag while the latter is a shorter etag. Not sure if that's expected:

`W/"0xe4661994dccf80c4268adf6a90931c8897b02176bc255e2e04d587e93f4a7f55:0x3270488a96edc78b047eeb35b1d877c82df75260341625b1649ba29d286756d7:0x9ca97e4165e9d62e775235a9bb6e0a13d5db8d170bd95afb2f5ec23531861b20:1"`
vs
`W/"0xa96192c2a84937a9eb619b4bd8855856bfde291697e97442eece64d9e724f1e8"`

**Comment by CharlieC3** [comment]
Confirmed that TX endpoints are getting cached by CF now! Thanks @rafaelcr @zone117x !
