### ISSUE TITLE
Postgres database error after db restart

### ISSUE THREAD

**Issue by CharlieC3** [hirosystems/stacks-blockchain-api#969]
**Describe the bug**
Seeing this error in the postgres database logs with the API running:
```
2022-01-11 19:11:53.839 GMT [1185] ERROR:  duplicate key value violates unique constraint "unique_microblock_hash"
2022-01-11 19:11:53.839 GMT [1185] DETAIL:  Key (microblock_hash)=(\x8cfc58122f935265442a2aa10172b9f65b18414228cd231c6f2f5702721296a2) already exists.
2022-01-11 19:11:53.839 GMT [1185] STATEMENT:
	        INSERT INTO microblocks(
	          canonical, microblock_canonical, microblock_hash, microblock_sequence, microblock_parent_hash,
	          parent_index_block_hash, block_height, parent_block_height, parent_block_hash, index_block_hash, block_hash,
	          parent_burn_block_height, parent_burn_block_hash, parent_burn_block_time
	        ) values($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
```

The error seems to resolve itself after 5 - 10 minutes, so I'm not sure how significant this is. @rafaelcr thinks it might have something to do with microblock re-orgs.

**To Reproduce**
1. Start an API + database + event stacks-node
2. Observe database logs

API version 1.0.4

**Comment by zone117x** [comment]
There's not really enough info here to diagnose or reproduce the issue, although it does seems like this would be a pretty critical issue if it was happening in production. Normally, it would result in the stacks-node effectively stalling and re-emitting the same event (causing the same error in the API) indefinitely. 

> The error seems to resolve itself after 5 - 10 minutes

I can only speculate here, but this seems to indicate that the event-emitter node was restarted and the likely offending `/new_microblock` event was dropped.

It's also possible that `/new_microblock` events were emitted in an unexpected way where that API ingestion and re-org code has never seen and does not know how to handle. 

It could also be a new kind of re-org scenario never before encountered, where the API does not know how to handle. 

In any case, we'd need the event-replay up until this time in order to replicate and figure out the source of the issue. @CharlieC3 if/when you encounter this again, could you snag that data?

**Comment by aulneau** [comment]
it seems that I've run into this error with two separate production api instances running. they have both failed at block `50422`, with this kind of error:

```json
{
  "code": "23505",
  "constraint": "unique_microblock_hash",
  "detail": "Key (microblock_hash)=(\\x4de76d9f174109a30f0ff4237495c4af543576efa94c453374b54052e5523319) already exists.",
  "file": "nbtinsert.c",
  "length": 288,
  "level": "error",
  "line": "656",
  "message": "error processing core-node /new_microblocks: error: duplicate key value violates unique constraint \"unique_microblock_hash\" duplicate key value violates unique constraint \"unique_microblock_hash\"",
  "name": "error",
  "routine": "_bt_check_unique",
  "schema": "public",
  "severity": "ERROR",
  "stack": "error: duplicate key value violates unique constraint \"unique_microblock_hash\"\n    at Parser.parseErrorMessage (/app/node_modules/pg-protocol/src/parser.ts:369:69)\n    at Parser.handlePacket (/app/node_modules/pg-protocol/src/parser.ts:188:21)\n    at Parser.parse (/app/node_modules/pg-protocol/src/parser.ts:103:30)\n    at Socket.<anonymous> (/app/node_modules/pg-protocol/src/index.ts:7:48)\n    at Socket.emit (node:events:390:28)\n    at addChunk (node:internal/streams/readable:315:12)\n    at readableAddChunk (node:internal/streams/readable:289:9)\n    at Socket.Readable.push (node:internal/streams/readable:228:10)\n    at TCP.onStreamRead (node:internal/stream_base_commons:199:23)",
  "table": "microblocks",
  "timestamp": "2022-02-28T14:21:50.434Z"
}

```

**Comment by rafaelcr** [comment]
@CharlieC3 have you seen this error again after the 3.0.1 upgrade? I believe this might have been fixed with the constraint check I added when inserting microblocks

**Comment by CharlieC3** [comment]
@rafaelcr I haven't seen this error in a while, and it makes sense that the constraint check you added would help prevent this. We can close this issue and reopen if I happen to see it.
